In [29]:
a=[1,2,3,4,5,12,34,21,32,76,45,76,97,34,11,22,33,44,221,345,765,234]

In [2]:
import numpy as np

In [30]:
len(a)

22

In [12]:
a=np.array(a)

In [35]:
c=np.random.choice(a,[2,5],p=[0.9,0.05,0.05,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])

ValueError: 'a' and 'p' must have same size

In [38]:
c

array([[1, 1, 3, 1, 1],
       [1, 1, 1, 1, 1]])

In [39]:
a=np.random.rand(10,5)

In [41]:
a

array([[0.52317228, 0.72400183, 0.01907692, 0.62931414, 0.6656919 ],
       [0.16317517, 0.92842379, 0.96675778, 0.36161992, 0.02081595],
       [0.33246488, 0.53032567, 0.64119094, 0.24484992, 0.28345661],
       [0.96099904, 0.49590168, 0.36974968, 0.64543794, 0.09848384],
       [0.31522795, 0.39568945, 0.93025887, 0.63868263, 0.5250326 ],
       [0.87921923, 0.67930385, 0.47969983, 0.32551738, 0.76236534],
       [0.43659228, 0.1785268 , 0.05340793, 0.45666579, 0.81441029],
       [0.651728  , 0.13699594, 0.70028636, 0.46328132, 0.387214  ],
       [0.46380804, 0.43448714, 0.13097228, 0.24921364, 0.06118587],
       [0.29042994, 0.02958538, 0.3715984 , 0.96972786, 0.95428299]])

In [45]:
a=np.random.normal(10,5,[10,5])

In [46]:
a

array([[11.17448224,  8.33710534, 14.15433043, 19.08562042, 10.88366251],
       [18.73222822, 14.52798744, 10.63799376,  6.42123802, 17.04206329],
       [16.25766593, 15.35072159,  9.15549793, 11.06110743, 12.13875004],
       [10.49049025, 11.0514929 , 13.80084267,  8.17691331, 20.490963  ],
       [11.91102999,  4.9542661 ,  6.26835545, 11.38468171, -1.497081  ],
       [ 5.19907969, 13.93127328, 12.34172561,  9.13019796, 13.73508429],
       [12.18062371,  2.90573475,  8.25086697, 14.20668314, -1.11118895],
       [ 2.73430281, 10.44955503,  6.49155252,  7.96139228,  9.77168781],
       [16.06385554,  4.81873415, 16.07323353,  8.29028129, 12.54663726],
       [-0.4237249 ,  8.85065859, 17.50580912, 12.01356615,  1.70332448]])

In [3]:
np.float(True)

C:\Users\HP\AppData\Local\Temp/ipykernel_4756/4002684417.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.float(True)


1.0

In [51]:
asd=[1,4,56,7]

In [52]:
asd[0,2]

TypeError: list indices must be integers or slices, not tuple

In [58]:
asd=np.random.normal(0,3,[4,32]).reshape(16,8)

In [60]:
asd

array([[ 0.78780235, -2.15873349,  1.91856512, -2.70121755,  1.6718145 ,
         2.77164486,  3.47682978, -3.37068033],
       [-2.24903825, -0.16717714, -0.75416367,  3.02271737, -1.18153334,
        -1.92514302, -0.04603449,  1.61459639],
       [ 3.26332959, -3.19651996,  2.93941141, -0.52724178,  1.18841308,
         3.85596008,  3.90096935,  1.41646108],
       [ 1.66485022, -3.61121434, -2.37249562, -1.09785069, -3.15361157,
        -4.1739732 ,  3.51441792,  0.1895741 ],
       [-0.20906572,  5.1479738 , -1.36441041, -1.79536096, -1.20837438,
        -2.41548721, -2.07205421, -1.81650115],
       [-2.94399695,  3.50587011, -2.19363619, -8.96101415, -0.11835854,
        -0.33959846, -0.47375369,  2.04471275],
       [-1.46004811,  4.38515335,  3.37147907,  1.73232287, -5.19518734,
         3.31364389,  2.54803609,  1.39694061],
       [-1.48027825,  4.46412378, -1.60749293, -5.0545129 ,  2.84392143,
        -0.44592995, -3.36863276,  2.80559203],
       [ 0.46212553, -0.48743232

In [61]:
a,b=np.modf(asd)

In [62]:
a

array([[ 0.78780235, -0.15873349,  0.91856512, -0.70121755,  0.6718145 ,
         0.77164486,  0.47682978, -0.37068033],
       [-0.24903825, -0.16717714, -0.75416367,  0.02271737, -0.18153334,
        -0.92514302, -0.04603449,  0.61459639],
       [ 0.26332959, -0.19651996,  0.93941141, -0.52724178,  0.18841308,
         0.85596008,  0.90096935,  0.41646108],
       [ 0.66485022, -0.61121434, -0.37249562, -0.09785069, -0.15361157,
        -0.1739732 ,  0.51441792,  0.1895741 ],
       [-0.20906572,  0.1479738 , -0.36441041, -0.79536096, -0.20837438,
        -0.41548721, -0.07205421, -0.81650115],
       [-0.94399695,  0.50587011, -0.19363619, -0.96101415, -0.11835854,
        -0.33959846, -0.47375369,  0.04471275],
       [-0.46004811,  0.38515335,  0.37147907,  0.73232287, -0.19518734,
         0.31364389,  0.54803609,  0.39694061],
       [-0.48027825,  0.46412378, -0.60749293, -0.0545129 ,  0.84392143,
        -0.44592995, -0.36863276,  0.80559203],
       [ 0.46212553, -0.48743232

In [63]:
asdf=np.ones((3,4))

In [64]:
asdf=np.array([1,4,3,4,3,4])

In [65]:
asdf=np.exp(asdf)

In [66]:
asdf

array([ 2.71828183, 54.59815003, 20.08553692, 54.59815003, 20.08553692,
       54.59815003])

In [67]:
np.e

2.718281828459045

In [68]:
np.e**4

54.59815003314423

In [70]:
np.maximum(asdf,asd)

ValueError: operands could not be broadcast together with shapes (6,) (16,8) 

In [71]:
a=np.random.randint(-3,3,[3,2])

In [76]:
b=np.random.randint(-3,3,[3,2])

In [79]:
a

array([[ 1, -3],
       [-3, -3],
       [ 0,  0]])

In [80]:
b

array([[-1, -3],
       [-1,  1],
       [ 0,  2]])

In [77]:
np.maximum(a,b)

array([[ 1, -3],
       [-1,  1],
       [ 0,  2]])

In [81]:
np.fmax(a,b)

array([[ 1, -3],
       [-1,  1],
       [ 0,  2]])

In [82]:
np.mod(a,b)

C:\Users\HP\AppData\Local\Temp/ipykernel_18436/3499680283.py:1: RuntimeWarning: divide by zero encountered in remainder
  np.mod(a,b)


array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [83]:
np.mod(b,a)

C:\Users\HP\AppData\Local\Temp/ipykernel_18436/2975056474.py:1: RuntimeWarning: divide by zero encountered in remainder
  np.mod(b,a)


array([[ 0,  0],
       [-1, -2],
       [ 0,  0]], dtype=int32)

In [90]:
asd=[6,1,2,3]

In [91]:
asd=np.argsort(asd)

In [92]:
asd

array([1, 2, 3, 0], dtype=int64)

In [96]:
asd=np.array([1,4,1,5,6,7,7,8])

In [100]:
asd.sort()

In [101]:
asd

array([1, 1, 4, 5, 6, 7, 7, 8])

In [102]:
np.sort(asd)

array([1, 1, 4, 5, 6, 7, 7, 8])

In [5]:
'''
asd
'''

'\nasd\n'

In [6]:
#asd

In [7]:
'''you
smwt'''

'you\nsmwt'

In [8]:
a=1


In [9]:
b=a

In [10]:
b=10

In [11]:
a

1

In [12]:
a=[1,2,3]

In [13]:
b=a

In [14]:
b[0]=100

In [15]:
a

[100, 2, 3]

In [72]:
import pandas as pd 

In [73]:
a=pd.Series([1,2,3])

In [74]:
a[0]='asd'

In [75]:
a=pd.Series([1,2,3],index=[0,1,2])

In [76]:
a[0]='asd'

In [77]:
a=pd.Series([1,2,3],index=['x','y','z'])

In [78]:
a[0]=1

In [79]:
a[0]='asd'

ValueError: invalid literal for int() with base 10: 'asd'

In [48]:
a

0    1
1    2
2    3
dtype: int64

In [49]:
a[0]='asd'

In [51]:
a[0]="asd"

ValueError: invalid literal for int() with base 10: 'asd'

In [50]:
a=pd.Series([1,2,3],index=["x",'y',"z"])

In [30]:
a

x    1
y    2
z    3
dtype: int64

In [44]:
a[0]=2

In [45]:
a

x    2
y    2
z    3
dtype: int64

In [25]:
a

x    asd
y      2
z      3
dtype: object

In [26]:
a[-1]

3

In [27]:
a[0]

'asd'

In [28]:
a[0]='asd'

In [80]:
data={'site':['asd','fgh','jkl'],'age':[10,11,12]}

In [81]:
df=pd.DataFrame(data)

In [83]:
df.loc[[0,1]]

site  age
0  asd   10
1  fgh   11

In [87]:
ad="E:\desktop\核心（新版）\10.知识图谱\医疗知识图谱资料\05医疗知识图谱问答机器人\QAMedicalKG\data\medical.json"

In [98]:
df=pd.read_json(r"E:\desktop\核心（新版）\10.知识图谱\医疗知识图谱资料\05医疗知识图谱问答机器人\QAMedicalKG\data\medical.json",lines=True)

In [104]:
print(df.head())

                                    _id       name  \
0  {'$oid': '5bb578b6831b973a137e3ee6'}   肺泡蛋白质沉积症   
1  {'$oid': '5bb578b6831b973a137e3ee7'}        百日咳   
2  {'$oid': '5bb578b6831b973a137e3ee8'}        苯中毒   
3  {'$oid': '5bb578b6831b973a137e3ee9'}    喘息样支气管炎   
4  {'$oid': '5bb578b6831b973a137e3eea'}  成人呼吸窘迫综合征   

                                                desc          category  \
0  肺泡蛋白质沉积症(简称PAP)，又称Rosen-Castle-man-Liebow综合征，是...  [疾病百科, 内科, 呼吸内科]   
1  百日咳(pertussis，whoopingcough)是由百日咳杆菌所致的急性呼吸道传染病...  [疾病百科, 儿科, 小儿内科]   
2  苯(benzene)是从煤焦油分馏及石油裂解所得的一种芳香烃化合物，系无色有芳香气味的油状液...       [疾病百科, 急诊科]   
3  喘息样支气管炎(asthmatoidbronchitis)又称哮喘性支气管炎，泛指一组喘息表...  [疾病百科, 内科, 呼吸内科]   
4  成人呼吸窘迫综合征简称ARDS，是一种继发的，以急性呼吸窘迫和低氧血症为特征的综合征。又称休...  [疾病百科, 内科, 呼吸内科]   

                                             prevent  \
0       1、避免感染分支杆菌病，卡氏肺囊肿肺炎，巨细胞病毒等。\n2、注意锻炼身体，提高免疫力。   
1  1、控制传染源：在流行季节，若有前驱症状应及早抗生素治疗。\n2、切断传播途径：由于百日咳杆...   
2  对于急性中毒患者，可以立即脱离现场至空气新鲜处，脱去污染的衣着，并用肥皂水或清水冲洗污染的皮...   
3  根据上